- example/src/App.js
- example/src/forms.json
- package-lock.json
- package.json
- src/builder.js
- src/index.js
This PR adds mainly the initial builder with a basic support of the common fields. As well as an example of usage
> Add builder

- example/package-lock.json
- example/src/App.js
- package-lock.json
- package.json
- src/Fields/Phone/index.js
- src/index.js
📌 References
Issue:
🎩 What is the goal?
Add Phone Input in the project
🔧 How is it being implemented?
Create PhoneInput
Add necesary dependencies
Render Phone component in App.js
> Add phone component

- example/src/_forms.json
- example/src/forms.json
- src/Fields/Select/_index.js
- src/Fields/Select/index.js
- src/Questions/Select/index.js
- src/builder.js
This PR adds supports for nested dependent questions
> Dependent questions

- package-lock.json
- package.json
- src/Questions/Checkbox/__tests__/checkbox.test.js
- src/Questions/Checkbox/index.js
This PR adds testing on the checkbox question using react testing library. It includes some improvements such as:
- Support for passing a markdown callback fn
- Remove unneed code
- Rename some params
- Some refactoring
On the integration test we'll do a more valuable test, checking form values. But this one covers and make sure it works as expected. There is one thing left which is the custom component this should just be UI replacement but not the business logic. We should be thinking on what and how to overwrite the styling that can change. May be using variants
> Checkbox question

- example/package-lock.json
- package-lock.json
- package.json
- src/Fields/MyModal/index.js
- src/Questions/Checkbox/Checkbox.stories.js
- src/Questions/Checkbox/__tests__/checkbox.test.js
- src/Questions/Checkbox/index.js
- feat related with the checkbox storybook.
- feat: "defaultChecked" added to the checkbox component, now  we can have a checkbox checked when the page is loaded without any user action.
2º commit : 
- feat: storybook changes with new checkbox stories:
- checkbox default
- checkbox error
- checkbox with link
> feat: storybook related with the checkbox component

- CHANGELOG.md
- example/package-lock.json
- example/src/App.js
- example/src/forms.json
- package-lock.json
- src/Questions/Checkbox/index.js
- src/builder.js
- src/index.js
test:
-  final user experience 
fix:
- QuestionCheckbox: missredirection in href used to open a new tab and open the modal too.
- formbuilder: export Modal and define that now checkboxCustomized can receive OnLinkClick
> Checkbox storybook

- example/package-lock.json
- package-lock.json
- package.json
- src/Fields/Select/index.js
- src/Questions/Country/__tests__/country.test.js
- src/Questions/Country/country.stories.js
- src/Questions/Country/index.js
feat: now country handles a custom list of countries  8c320e1
refactor:  
- customOrder renamed to priorityOrder 
- isMobile == false is removed 
- Now priorityOrder is a string array with the name of the countries that you want to be displayed the first in the list. 
Ex: priorityOrder: ['Spain','United Kingdom']
Testing:  73237ec
- The place holder
- The label existence
- The select component can change its value and select another option
- Check that the custom order countries work, sending GB and selecting the 1º item to check that is UK 
- Custom list of countries are ordered as they are sent 
- Label tag is not displayed when is null
- Error message is displayed
Documentation --> storybook: c0494bc
Default country
Country with show error message
Country with UK as the first option …
> Question country

- example/package-lock.json
- example/src/forms.json
- src/Fields/Select/index.js
- src/Questions/Country/index.js
- src/Questions/Select/index.js
refactor: 
- country and select now can have a placeholder we have considered that it is more clean and logical for the flow
> feat: placeholder option in select & country Questions

- src/Fields/Phone/index.js
- src/Questions/Country/__tests__/country.test.js
- src/Questions/Phone/index.js
e664cca the new test related with the new logistic of the selects 
019226c &&  105740d removing the required of the phone input
> Placeholder

- src/Questions/Markdown/index.js
- src/Questions/Radio/index.js
feat: markdown text will be displayed now over radios buttons
refactor: changed the logic behind radio buttons multiple radio buttons in the same div to work better with the style, and less code in json to generate them
> feat: markdown

- src/Fields/Markdown/index.js
- src/Questions/Checkbox/index.js
- src/Questions/Markdown/index.js
- src/builder.js
now markdown field will manage all the logic related with links due it is its responsibility, this should not be managed out of this scope.
> refactor: markdown onLinkOpen

- src/Questions/Input/__tests__/input.test.js
- src/Questions/Input/index.js
- src/Questions/Input/input.stories.js
6d96c9d  && 5ea04c0: 
InputQuestion Stories: 
- Default Input
- Input error required
- Input error pattern
- Input with icon
- Input with icon & tooltip
- input with custom tooltip
- input with icon name not found
1720705:  fixing test due to the new logic. Text "Icon Not found" displayed when there is an error in the icon name.
f826a36: removing displaying tooltip when there is no text or tooltip
> Input stories svg fixed

- src/Questions/Radio/__tests__/radio.test.js
- src/Questions/Radio/index.js
- src/Questions/Radio/radio.stories.js
db555cd fixing the aligned of labels and radios now library will send them aligned, ivan will not add more css to do this.
9aa9dc8 Testing:
- Check that text as markdown is rendered
- Labels for radioButtons
- radioB values
- Error Message
- radio can be selected
e7f03c7 3 stories for radioB i think that is really simple i can't do too much interesting in stories...
1) Default radiob
2) Text in markdown 
3) Error displayed
> Radio question

- README.md
> NPM link update

- package-lock.json
- package.json
- rollup.config.js
making a minimize version of our package
> testing minimize package

- src/Fields/Phone/index.js
**Bug**:
on registerconfig non required and it is not defined exception thrown due to registerconfig.required non defined
> Fixing non required bug

- example/src/App.js
- src/Fields/Error/index.js
- src/Fields/Select/index.js
- src/Questions/Checkbox/index.js
- src/Questions/Country/index.js
- src/Questions/Date/index.js
- src/Questions/Input/index.js
- src/Questions/MultipleCheckboxes/index.js
- src/Questions/Phone/index.js
- src/Questions/Radio/index.js
- src/Questions/Select/index.js
- src/builder.js
Changing the components to improve the accessibility of each one
> Accessibility components rfb

- src/Questions/Markdown/__tests__/markdown.test.js
- src/Questions/Select/__tests__/select.test.js
- Markdown Question test added
- Select Question test added
- npm test
> Tests added on Select & Markdown Questions

- src/Fields/Error/index.js
- src/Fields/Select/index.js
- src/Questions/Checkbox/index.js
- src/Questions/Country/index.js
- src/Questions/Date/index.js
- src/Questions/Input/index.js
- src/Questions/Markdown/index.js
- src/Questions/MultipleCheckboxes/index.js
- src/Questions/Phone/index.js
- src/Questions/Radio/index.js
- src/Questions/Select/index.js
- src/builder.js
> Better theme logic

- src/Questions/Checkbox/index.js
- src/Questions/Country/index.js
- src/Questions/Date/index.js
- src/Questions/Input/index.js
- src/Questions/Markdown/index.js
- src/Questions/MultipleCheckboxes/__tests__/multipleCheckboxes.test.js
- src/Questions/MultipleCheckboxes/index.js
- src/Questions/Phone/index.js
- src/Questions/Radio/index.js
- src/Questions/Select/index.js
- src/builder.js
c0b9594: removing the customComponent from the all questions. This is never used and we should not prepare the library for all this cases we generate and form not a form with all the posibilities.
d2ca623: Same kind of error message and structure repeated. 
https://user-images.githubusercontent.com/79102959/134825849-fc75ac67-8549-44ac-9f19-75f32dcf656d.mov
displaying that it is still working after the refactor in errorMessages.
12202fd: adding testing
> Removing stuff

- .husky/commit-msg
- commitlint.config.js
- package-lock.json
- package.json
- Adding CommitLint and Husky libraries to control our commit descriptions
1. Install dependencies: Run `npm install` command on your console
2. Add a new file and run the following commands:
- `git add .`
-  `git commit -m "foo: this will fail"` (This will lead to an error)
- `git commit -m "feat: new file"` (This commit will run smoothly)
> feat: add commitLint and Husky

- README.md
Add to readme information about accessibility in the library
> docs: add accessibility section to readme

- src/Fields/Markdown/index.js
Remove aria-label in checkboxes links
> refactor: updated aria-label in checkbox links

- example/src/forms.json
- package-lock.json
- src/Questions/MultipleCheckboxes/index.js
> feat(multiplecheckbox): add disable others option

- src/Questions/Date/__tests__/date.test.js
Fix date test according with the new dropdown date library
> fix: date picker test

- src/builder.js
Add dependent question to multicheckboxes
> feat(builder): add dependent question to multicheckboxes

- src/Fields/Date/index.js
Change select date order only in front.
> fix(dateQuestion): select date order

- src/Questions/County/data/countryAndCounties.js
Change gb, ie, fr and se regions data
> feat(regions): change gb, ie, fr and se regions data

- src/Fields/Phone/index.js
Add ltr attribute to phone question
> feat(phone): add ltr attribute

- README.md
- src/Questions/Phone/__tests__/phone.test.js
- src/Questions/Phone/index.js
Add default country value to phone question
(add unit test and update readme with this feature)
> feat(mobile): add default country value

- src/Questions/Phone/index.js
> fix(form): remove ? typo

- src/builder.js
Add array conditions to dependent question in multiple_checkboxes
> feat: add array conditions to dependent question in multiple_checkboxes

- src/Questions/Textarea/index.js
> fix: textarea errorMessage

- src/Questions/Textarea/index.js
> fix(text-area): use proper sep for countlimit

- src/Fields/Error/index.js
- src/Questions/MultipleCheckboxes/index.js
> fix(error-message): use errorStyles prop instead of overwrite sx

- src/builder.js
> refactor(builder): set component props

- src/Fields/AsyncReactSelect/index.js
- src/Fields/Select/index.js
> fix(react-select): use id to prevent hydration errors

- src/Questions/ImageInput/index.js
- src/builder.js
> feat(questions): add image input question type

- README.md
Added Code Climate Badges
- Related https://github.com/onebeyond/maintainers/issues/113
> Added codeclimate badges

- .github/workflows/code-climate-test-coverage.yml
- .github/workflows/openssf-scorecard.yml
fix: allowed-endpoints for gh actions
> fix: allowed-endpoints for gh actions

- .github/workflows/code-climate-test-coverage.yml
- .github/workflows/openssf-scorecard.yml
ci: set egress-policy to audit
> ci: set egress-policy to audit

- .github/workflows/code-climate-test-coverage.yml
- .github/workflows/openssf-scorecard.yml
- README.md
fix: get back egress-policy block for harden runner
> fix: get back egress-policy block for harden runner

- .github/workflows/cd.yml
fix: revert to egress-policy: audit for cd gh action
> fix: revert to egress-policy: audit for cd gh action

- README.md
- example/package-lock.json
- example/src/forms.json
- package-lock.json
- package.json
- src/Questions/Recaptcha/__tests__/recaptcha.test.js
- src/Questions/Recaptcha/index.js
- src/__tests__/builder.test.js
- src/__tests__/forms.json
- src/builder.js
- Added reCAPTCHA component.
- Added tests and docs in the Readme. Note that the test for the component is rather simple because we would just testing a third-party library.
- [ALD-11](https://csmdigital.atlassian.net/browse/ALD-11) -> Adding the reCAPTCHA component.
- [ALD-12](https://csmdigital.atlassian.net/browse/ALD-12) -> Receiving the key from the form data passed to the library.
Tested both manually and with unit tests to verify that:
- The form submits when there's no reCAPTCHA.
- The form submits when there's reCAPTCHA but it doesn't detect a bot.
- The reCAPTCHA modal shows to verify the user is not a bot when it detects bot-like behavior. Upon completing the reCAPTCHA (selecting images that match a word) the form submits normally.
Note that at the end of the testing the …
> ALD-11 | Add reCAPTCHA component

- package-lock.json
- package.json
- src/Fields/Phone/index.js
> fix: remove direct css import from Phone

- release-please-config.json
To avoid conflicts with previous releases of the library, the configuration has been modified to include the component name in the tag.
Avoid potential conflicts when releasing under new tags.
> fix: add component name in github release tag

- README.md
- This option is missing from the docs and could be discovered only by walking through the source code. It is now documented in the main README.md file
N/A
- Tired of checking source code all the time for the exact name
I don't think it has to be tested in any way but let me know.
> docs(multiple-checkboxes): add `disableOthers` to option config docs
